services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "${MQ_PORT}:${MQ_PORT}"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}

  postgres:
    image: postgres
    container_name: postgres_docker
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./cmd/migrate/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:$POSTGRES_PORT/$POSTGRES_DB?sslmode=disable", "up"]
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
  
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "${SMTP_PORT}:${SMTP_PORT}" # SMTP server port
      - "8025:8025" # Web UI port

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: api
    restart: on-failure
    depends_on:
      - postgres
      - migrate
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT}
    ports:
      - "8080:8080"

  emails:
    build:
      context: .
      dockerfile: ./cmd/emails/Dockerfile
    container_name: emails
    restart: on-failure
    depends_on:
      - postgres
      - migrate
      - rabbitmq
      - mailhog
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT}
      MQ_USERNAME: ${MQ_USERNAME}
      MQ_PASSWORD: ${MQ_PASSWORD}
      MQ_HOST: rabbitmq
      MQ_PORT: ${MQ_PORT}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: mailhog
    ports:
      - "6060:6060"